@VivaApiProject_HostAddress = http://localhost:5168

GET {{VivaApiProject_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{VivaApiProject_HostAddress}}/api/countries
Accept: application/json

